---
title: "narrativas"
author: "Ricardo Mayer"
date: "January 3, 2017"
output:
  pdf_document: default
  html_document: default
---

## Choques financieros externos

Los choques financieros globales

### Un choque de TPM externas

### Un choque de 


### Un choque de tasas de interes externas 

1. Inicio: la FED o el ECB suben sus tasas de interes de politica de 0.75 a 1.50

2. Aumenta el spread de tasas (domestica vs extranjera), se convierte en un presion a la devaluacion de la 
moneda local o al aumento de la tasa de interes domestica o una combinacion de ambas

3. Efectos inmediatos:

   - (if aumento de tasas) Aumento del costo de financiamiento domestico y externo:
      + Impacto: encarecimiento de nueva deuda, de deuda anterior con tasa variable y de refinanciamiento
      + Dato: deuda corporativa, corto versus largo plazo, tasa fija versus variable.
      + Dato: deuda de hogares, consumo, hipotecaria y otros de largo plazo (p.e. estudios)
      + Efecto macro: menor consumo financiado con deuda
      + Efecto macro: aumento de morosidad, defaults corporativos o personal es, cae valor de activos del sector financiero
      + Efecto macro: presion a la baja en el nivel de precios agregados

   - (if depreciacion) Descalce cambiario en las hojas de balance: 
      + Impacto: Devaluacion del colateral, aumento del costo de la deuda en divisas, necesidad de desapalancar
      + Impacto: Aumento del costo domestico de pagar deuda extranjera, disminucion de liquidez publica y privada
      + Dato: Requiere mirar composicion en moneda nacional y extranjera de hojas de balance. 
      + Dato: Si no es posible contar con hojas de balance, al menos ver composicion de la deuda
      + Efecto macro: caida de la inversion privada
      + Efecto macro: menor espacio para la politica fiscal
      + Efecto macro: aumento del riesgo comparativo o pais, si la perdida de liquidez es muy grande y amenaza solvencia corporativa o fiscal
      
   - (if depreciacion) Aumento del valor en moneda local de las exportaciones 
      + Aumento de utilidades en moneda local, posible efecto en el mediano plazo en el empleo y en el producto
      
   - (if depreciacion) Aumento del valor en moneda local de las importaciones
      + Caida de utilidades en moneda local
      + Traspaso parcial o gradual a precios domesticos (pass through)
   
      
4. Respuestas de politica     

   - Si el tipo de cambio no es flexible (pegged or fixed), hay perdida de reservas
   - Si hay depreciacion (via devaluacion o porque hay tipo de cambio flexible), hay presiones al alza en los precios, eso puede limitar estimulos via gasto
   - El BC podria optar por subir la tasa de politica o disminuir la base monetaria, para evitar un aumento del diferencial de tasas, pero esto es dificil si la economia se encuentra al borde o en franca recesion
   - Incluso en casos sin pegging podria querer administrar las reservas internacionales pare evitar un excesos de volatilidad.





## Un choque de terminos de intercambio 

1. Inicio: 
    a. Caida del precio de un bien de exportacion (metales, hidrocarburos, cafe, soya) (commodity-market specific shock), no esta fuertemente relacionado con un cambio en el crecimiento mundial
    b. World demand shock (a positive shock increases prices of both exports and imports)
    c. Globalization shock

2. Efectos inmediatos:

   - Empeoramiento de la balanza comercial y cuenta corriente, presion a la depreciacion de la moneda local
   - Empeoramiento de la hoja de balance de empresas exportadores y en el caso de empresas relacionadas con el 
   Estado, empeoramiento de la hoja de balance del sector publico
   - Caida del empleo directo o indirecto asociado del empleo en sector productor
   - Caida del ahorro domestico y presion al alza de la tasa de interes
   - Efectos sectoriales sobre el empleo y la inversion y su contagio a otros sectores depende del precio especifico que cambia y de la persistencia del choque


### Que diferencias existen en los efectos de una caida del precio de minerales, hidrocarburos y alimentos?

### Choque de precios de metales y mineria, pais exportador (chile, peru).

1. Inicio: Cae el precio del cobre

2. Efectos inmediatos:

   - Caen ingresos corporativos de mineras, publicas y privadas.
   - Empeora balanza comercial, a menos que el efecto ingreso sea muy fuerte sobre las importaciones. 
   - Disminuye la oferta de dolares, presion a la depreciacion de la moneda local
       + Bajo tipo de cambio flexible, al depreciacion ocurre (mejorando en algo su rentabilidad en moneda local)
       + Bajo peg, o fijo, hay perdida de reservas internacioales. Dependiendo del tamano  y persistencia del shock, puede haber una devaluacion (de no haber devaluacion, no hay mejora parcial de )
   - Empeoran hojas de balance de esas empresas, por efecto en el valor presente de sus ventas futuras. Este efecto es peor si no se deprecia la moneda local.
   - Cae inversion de empresas mineras
   - Cae la produccion de cobre, suvizando en algo la caida del precio (chile+peru tienen algo de poder de mercado)
   - Se reduce la actividad de empresas o independientes relacionadas a las mineras: disminucion de ingresos y del empleo
   - Cae recaudacion fiscal por menores ventas de empresas privadas y menores aportes de empresas estatales
     + Si la perdida de rentabilidad de la empresa estatal es importante y suficientemente transitoria, es posible que el Gobierno Central decida inyectar capital para evitar un aumento sustantivo de los costos financieros y asegurar su liqudez. Si el gobierno central no tiene el espacio suficiente para hacer dicha capitalizacion, se avecina una crisis de la minera estatal 
     
   - Efecto sobre el empleo nacional: depende de cuan externalizados esten sus servicios no escenciales y de cuanto comercio se haya instalado alrededor de las mineras, pero la actividad minera al no estar muy encadenada a otras industrias productivas, genera un impacto mas acotado en el empleo total del pais.


3. Efectos indirectos

   - 




### Choque de precios de petroleo, pais exportador (ecuador, venezuela, colombia ... y mexico?) y gas natural (Bolivia).

1. Inicio: Cae el precio del petroleo (y/o gas natural)

2. Efectos inmediatos:

   - Caen ingresos corporativos de petroleras, publicas y privadas.
   - Empeora balanza comercial, a menos que el efecto ingreso sea muy fuerte sobre las importaciones. 
   - Disminuye la oferta de dolares, presion a la depreciacion de la moneda local
       + Bajo tipo de cambio flexible, al depreciacion ocurre (mejorando en algo su rentabilidad en moneda local)
       + Bajo peg, o fijo, hay perdida de reservas internacioales. Dependiendo del tamano  y persistencia del shock, puede haber una devaluacion (de no haber devaluacion, no hay mejora parcial de )
   - Empeoran hojas de balance de esas empresas, por efecto en el valor presente de sus ventas futuras. Este efecto es peor si no se deprecia la moneda local.
   - Cae inversion de empresas petroleras
   - Cae la produccion de petroleo (puede venezuela moverse idnependiente de opep?), suvizando en algo la caida del precio (venezuela+mexico tienen algo de poder de mercado)
   - Se reduce la actividad de empresas o independientes relacionadas a las mineras: disminucion de ingresos y del empleo
   - Cae recaudacion fiscal por menores ventas de empresas privadas y menores aportes de empresas estatales
     + Esto es probablemente mas importante que en el caso del cobre, porque en ALC el petroleo aun esta mas concentrado en el sector publico que el petroleo o el gas natural
     + Si la perdida de rentabilidad de la empresa estatal es importante y suficientemente transitoria, es posible que el Gobierno Central decida inyectar capital para evitar un aumento sustantivo de los costos financieros y asegurar su liqudez. Si el gobierno central no tiene el espacio suficiente para hacer dicha capitalizacion, se avecina una crisis de la petrolera estatal 
   - Efecto sobre el empleo nacional: el efecto directo es probablemente pequenho. En el caso de que genere una caida masiva del ingresos fiscales, afecta al empleo publico y a los proveedores del estado.



3. Efectos indirectos

   - 


   
     

### Choque de precios de comida, pais exportador (argentina, uruguay, guatemala, paraguay).

1. Inicio: Cae el precio de carne, soya, cafe, harinas

2. Efectos inmediatos:

   - Caen ingresos de productores.
     + Mercado exportador concentrado con pocos y grandes empresas productoras? Mayor posibilidad de suavizar el shock via instrumentos fiancieros
     + Mercado con presencia importante de pequenhos productores? Mayor caida del consumo y del empleo.
   - Empeora balanza comercial, a menos que el efecto ingreso sea muy fuerte sobre las importaciones. 
   - Disminuye la oferta de dolares, presion a la depreciacion de la moneda local
       + Bajo tipo de cambio flexible, al depreciacion ocurre (mejorando en algo su rentabilidad en moneda local)
       + Bajo peg, o fijo, hay perdida de reservas internacioales. Dependiendo del tamano  y persistencia del shock, puede haber una devaluacion (de no haber devaluacion, no hay mejora parcial de )
   - Empeoran hojas de balance de esas empresas, por efecto en el valor presente de sus ventas futuras. Este efecto es peor si no se deprecia la moneda local. 
   - Cae inversion de empresas productoras de alimentos. Si es un sector que se caracteriza por baja participacion en el stock de capital, su impacto sobre la inversion total sera menos pronuciada que en el caso minero o hidrocarburos
   - Cae la produccion de soya, cafe, carne, etc.
   - Cae recaudacion fiscal por menores ventas de empresas privadas y menores aportes de empresas estatales
     + Esto es probablemente menos importante en el caso del cobre y el petroleo, porque en ALC los productores y exportadores de alimentos son mayoritariamente privados.

   - Efecto sobre el empleo nacional: son sectores productivos mas trabajo-intensivo que el petroleo y cobre, su efecto directo sobre el empleo total es importante y sobre el consumo de los hogares tambien, con un impacto probable sobre la capacidad de edaudamiento y pago de los hogares.
   
   
 

3. Efectos indirectos

   - Canal financiero:
     + Hogares:
     + Empresas:
     


  
   
