---
title: "Mapa de ALC post todo"
author: "Ricardo Mayer"

output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
  pdf_document: default
  word_document: default
  
params:
  end_year: 2015
  start_year: 1990
  is_html: TRUE
  dygraphs_plots: TRUE
  ggplot2_plots: TRUE
  path_prefix: 'V:/USR/RMAYER/cw/cap_estudio_2017/'

---


```{r knit_config, include=FALSE}

# knitr::opts_knit$set(root.dir = "./../")
knitr::opts_chunk$set(echo = FALSE)

```

```{r setup, echo=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::read_chunk("./../scripts/financial_script_alc.R")
```


```{r libraries}
```


```{r constants_and_functions, message=FALSE}
```


```{r load_data_sets}

```


```{r bk_loans_consum_dfs}
```

```{r credit_by_the_financial_sector_dfs}
```

```{r credit_to_private_sector_by_banks_dfs}
```

```{r credit_to_private_sector_dfs}
```


```{r credit_reporting_text}
```


```{r create_better_reporting_text}

make_ctables <- function(df) {
  df_pct4 <- 1
}



```

