---
title: "variables of interest"
author: "Ricardo Mayer"
date: "March 6, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "./../")
knitr::opts_chunk$set(echo = TRUE)
```

## A tentative list

### What variables are related to (lack of) resilience and policy oportunities?

#### Threats to financial sustainability

- Deuda externa total/publica/privada a PIB
- costo del servicio de la deuda a PIB
- Cartera vencida como porcentaje de prestamos
- TPM
- Tasa activa promedio

#### Structural fragilities

- export concentration (products). Top 1 over total, Top 3 over total, Herfindahl
- export concentration (markets). Top 1 over total, Top 3 over total, Herfindahl



##### In the public sector

1. fiscal deficit
2. tendency fiscal deficit
3. debt service ratio
4. expected primary deficits
5. debt half-life (summarize variables such as expected growth, interest, repayments, etc.)

6. Public enterprises solvency

Don't forget to specify the coverage of the fiscal variable (central, nfps, etc.)


## Data 

### Fiscal





